# Generated by Django 4.1.3 on 2022-11-27 11:39

import MyBlog.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), MyBlog.core.validators.validate_only_letters]),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), MyBlog.core.validators.validate_only_letters]),
        ),
    ]
