# Generated by Django 4.1.3 on 2022-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bloguser_first_name_bloguser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='profile_pic',
            field=models.ImageField(default='images/profile-img.webp', upload_to='pictures/'),
        ),
    ]
