# Generated by Django 4.1.3 on 2022-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bloguser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='profile_pic',
            field=models.URLField(),
        ),
    ]
