# Generated by Django 4.1.3 on 2022-12-14 10:26

import MyBlog.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='1', max_length=30, validators=[django.core.validators.MinLengthValidator(2), MyBlog.core.validators.validate_only_letters]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='1', max_length=30, validators=[django.core.validators.MinLengthValidator(2), MyBlog.core.validators.validate_only_letters]),
            preserve_default=False,
        ),
    ]
