# Generated by Django 4.1.3 on 2022-11-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bloguser_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='profile_pic',
            new_name='profile_image',
        ),
    ]
