# Generated by Django 4.1.7 on 2023-08-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bloguser',
            managers=[
            ],
        ),
    ]
