# Generated by Django 4.1.7 on 2023-08-18 17:50

import MyBlog.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_bloguser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bloguser',
            managers=[
                ('objects', MyBlog.accounts.managers.BlogUserManager()),
            ],
        ),
    ]
