# Generated by Django 4.1.3 on 2022-11-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('new_events', 'New Events'), ('courses', 'Courses')], max_length=20, null=True),
        ),
    ]
