# Generated by Django 4.1.3 on 2022-12-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_article_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='intro',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
