# Generated by Django 4.1.3 on 2023-02-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_first_name_alter_profile_last_name'),
        ('articles', '0007_alter_article_author_alter_article_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
        migrations.AddField(
            model_name='article',
            name='post_image',
            field=models.ImageField(default='1', upload_to='post_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(blank=True, choices=[('Published', 'Published'), ('Draft', 'Draft')], null=True),
        ),
    ]
