# Generated by Django 4.1.3 on 2023-02-14 07:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_image_url_article_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
