# Generated by Django 4.1.3 on 2023-02-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_image',
            field=models.ImageField(upload_to='articles/'),
        ),
    ]
