# Generated by Django 4.1.3 on 2023-02-20 08:57

import MyBlog.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_image',
            field=models.ImageField(upload_to='articles/', validators=[MyBlog.core.validators.validate_max_image_size]),
        ),
    ]
