# Generated by Django 4.1.7 on 2023-03-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Published')], null=True),
        ),
    ]
