# Generated by Django 4.1.7 on 2023-08-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Published')], default=0, null=True),
        ),
    ]
