# Generated by Django 4.1.3 on 2022-12-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoAboutApp',
        ),
    ]
