# Generated by Django 4.1.7 on 2023-03-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
