# Generated by Django 4.1.7 on 2023-03-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_blog', '0004_delete_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAboutApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
