# Generated by Django 4.1.7 on 2023-08-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_articlelike'),
        ('my_blog', '0007_delete_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
